name: Convert markdown to pdf

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker://pandoc/latex:2.16.2
        with:
          args: >-  # allows you to break string into multiple lines
            -f gfm 
            -t pdf
            -o white-paper.pdf
            README.md
            introduction.md
            governance.md
            business-model.md
            road-map.md
      - uses: actions/checkout@v2
        with:
          repository: delishes-io/web
          path: web
          token: ${{secrets.PANDOC}}
      - name: copy the generated pdf file and commit it to delishes-io/web
        run: |
          cd web
          git config user.name github-actions
          git config user.email songhaobei@gmail.com
          cp ../white-paper.pdf public/
          git add .
          git commit -m "[bot] updated wihte paper on web"
          git push
